### ISSUE TITLE
Mod will cause Shops to dissapear game will "super soft hang"

### ISSUE THREAD

**Issue by Pappystein** [janxious/ShopSeller#4]
With ShopSeller installed many planets will have shops that will be non existent &  cause a "hiccup" in game (game will stay static and nothing will happen until you click on the Argo Side menu.)  Game will act like it is stuck in a loop that can be broken when you click an option on the Argo Side menu.

Saveing the game and reloading in the same Battletech sesson does not solve this but Saving and closing Battletech itself will sometimes result in a store appearing on re-load.

Deleting Modtek Cache and Database seems to reduce the occurrence of issue but not eliminate it.
When I had Inner-sphere Map and it's associated Mods installed the issue was LESS than without it.   

This is with a pretty light load of mods (I think):
Quiet Darius (your fork)
SortByTonnage, MechResizer (You)
Ammo Cookoff RealityMachina
Attack Improvement and Turbine by Sheep-y
MPSark's  Health Popup and PunchinOut
PermanentEvasion, MechMaintencebycost, MeleeMover, Morphyum
CamZoom Agris
OnePointArmorStep Glucose

Issue appeared with BTML Injector from MPStark or from your Forks (both versions for 1.1.2 and for 1.2)

Will gladly provide any additional information you require.

**Comment by janxious** [comment]
As states in the README this mod is no longer supported.

**Comment by Pappystein** [comment]
Rgr thanks and sorry.  Didn't see that.  My bad.   Is there any chance for
a shop buyer?  Or does the game engine change preclude this?

On Aug 29, 2018 12:21 PM, "janxious" <notifications@github.com> wrote:

Closed #4 <https://github.com/janxious/ShopSeller/issues/4>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/janxious/ShopSeller/issues/4#event-1816106527>, or mute
the thread

**Comment by janxious** [comment]
There is nothing precluding this mod working with the new stuff,a nd I'm not necessarily against maintinaing it more. I just thought the new stuff replaced what I did. if not, then I can be convinced to work on it more. I haven't actually looked at the changes, just read them in the changelog.

**Comment by Pappystein** [comment]
In selling the game works like your mod did. However the game does not
allow multiple purchases.

**Comment by janxious** [comment]
@Pappystein https://github.com/janxious/ShopSeller/releases/tag/v0.4.3 new version

**Comment by Pappystein** [comment]
Thank you for re-addressing this mod!  It makes buying things so much easier!

**Comment by Pappystein** [comment]
Thank you for re-addressing this mod!  It makes buying things so much easier!
